name: Creativity Fitness
favicon: null
layout_spectrum: 0.89103
typography_spectrum: 0.80861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4817691056523472
  lightness: 0.3409004812128842
  saturation: 0.33802661928348243
  rhythmicContrast: 0.6010306621901691
purpose: []
